import React, { useState } from 'react';
import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';
import { ReportData } from '../../types';
import { Button } from '../common/Button';
import { FileDown } from 'lucide-react';
import { formatNumber } from '../../utils/helpers';
import { toast } from 'react-toastify';

interface PDFExportProps {
  reportData: ReportData;
}

export const PDFExport: React.FC<PDFExportProps> = ({ reportData }) => {
  const [loading, setLoading] = useState(false);

  const generatePDF = async () => {
    setLoading(true);
    try {
      const doc = new jsPDF('p', 'mm', 'a4');
      const pageWidth = doc.internal.pageSize.getWidth();
      const pageHeight = doc.internal.pageSize.getHeight();

      // Title
      doc.setFontSize(24);
      doc.setTextColor('#10B981');
      doc.text('CarbonVault Report', pageWidth / 2, 20, { align: 'center' });

      // User info
      doc.setFontSize(12);
      doc.setTextColor('#6B7280');
      doc.text(`Generated for: ${reportData.user.name}`, 20, 35);
      doc.text(`Email: ${reportData.user.email}`, 20, 42);
      doc.text(`Date: ${reportData.date.toLocaleDateString('en-US', {
        year: 'numeric',
        month: 'long',
        day: 'numeric',
      })}`, 20, 49);

      // Divider
      doc.setDrawColor('#E5E7EB');
      doc.line(20, 54, pageWidth - 20, 54);

      // Total emissions
      doc.setFontSize(18);
      doc.setTextColor('#111827');
      doc.text('Carbon Footprint Summary', 20, 65);

      doc.setFontSize(28);
      doc.setTextColor('#10B981');
      doc.text(`${formatNumber(reportData.totalEmissions)} kg CO₂e`, 20, 78);

      doc.setFontSize(12);
      doc.setTextColor('#6B7280');
      doc.text('Total annual emissions', 20, 88);

      // Category breakdown
      doc.setFontSize(14);
      doc.setTextColor('#111827');
      doc.text('Category Breakdown', 20, 105);

      let yPos = 115;
      Object.entries(reportData.categories).forEach(([category, value]) => {
        doc.setFontSize(11);
        doc.setTextColor('#374151');
        doc.text(`${category.charAt(0).toUpperCase() + category.slice(1)}:`, 20, yPos);
        doc.setTextColor('#10B981');
        doc.text(`${formatNumber(value)} kg CO₂e`, 80, yPos);
        yPos += 7;
      });

      // Achievements
      yPos += 10;
      doc.setFontSize(14);
      doc.setTextColor('#111827');
      doc.text('Achievements', 20, yPos);
      yPos += 8;

      doc.setFontSize(11);
      doc.setTextColor('#374151');
      doc.text(`Actions Completed: ${reportData.actionsCompleted}`, 20, yPos);
      yPos += 7;
      doc.text(`Total Points Earned: ${reportData.totalPoints}`, 20, yPos);

      // Insights
      if (reportData.insights.length > 0) {
        yPos += 10;
        doc.setFontSize(14);
        doc.setTextColor('#111827');
        doc.text('Key Insights', 20, yPos);
        yPos += 8;

        doc.setFontSize(10);
        doc.setTextColor('#4B5563');
        reportData.insights.slice(0, 3).forEach((insight) => {
          const lines = doc.splitTextToSize(`• ${insight}`, pageWidth - 40);
          doc.text(lines, 20, yPos);
          yPos += lines.length * 6;
        });
      }

      // Recommendations
      if (reportData.recommendations.length > 0) {
        yPos += 5;
        doc.setFontSize(14);
        doc.setTextColor('#111827');
        doc.text('Recommendations', 20, yPos);
        yPos += 8;

        doc.setFontSize(10);
        doc.setTextColor('#059669');
        reportData.recommendations.slice(0, 3).forEach((recommendation) => {
          const lines = doc.splitTextToSize(`✓ ${recommendation}`, pageWidth - 40);
          doc.text(lines, 20, yPos);
          yPos += lines.length * 6;
        });
      }

      // Footer
      doc.setFontSize(8);
      doc.setTextColor('#9CA3AF');
      doc.text(
        'Generated by CarbonVault - Track, Understand, Reduce',
        pageWidth / 2,
        pageHeight - 10,
        { align: 'center' }
      );

      doc.save(`carbonvault-report-${new Date().toISOString().split('T')[0]}.pdf`);
      toast.success('PDF report downloaded successfully!');
    } catch (error) {
      console.error('Error generating PDF:', error);
      toast.error('Failed to generate PDF');
    } finally {
      setLoading(false);
    }
  };

  return (
    <Button
      onClick={generatePDF}
      disabled={loading}
      className="min-w-[150px]"
    >
      <FileDown className="w-5 h-5" />
      {loading ? 'Generating...' : 'Export PDF'}
    </Button>
  );
};